// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDomf8CvWj7I1mx2FMwKpcXFytKfDsdN0Q',
    appId: '1:999607488029:web:c7d27e504e1277e33f00f4',
    messagingSenderId: '999607488029',
    projectId: 'ai-tumor-detect',
    authDomain: 'ai-tumor-detect.firebaseapp.com',
    storageBucket: 'ai-tumor-detect.firebasestorage.app',
    measurementId: 'G-XR1L365NXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM3kPUS9dN2x7Sa5AH8tw7czcx5zUuj3I',
    appId: '1:999607488029:android:323d83d1228d0cc03f00f4',
    messagingSenderId: '999607488029',
    projectId: 'ai-tumor-detect',
    storageBucket: 'ai-tumor-detect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC144ik579Z4QEuIZkABJSTq1BWYCDQS1A',
    appId: '1:999607488029:ios:258945edd505c8ce3f00f4',
    messagingSenderId: '999607488029',
    projectId: 'ai-tumor-detect',
    storageBucket: 'ai-tumor-detect.firebasestorage.app',
    iosBundleId: 'com.example.aiTumorDetect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC144ik579Z4QEuIZkABJSTq1BWYCDQS1A',
    appId: '1:999607488029:ios:258945edd505c8ce3f00f4',
    messagingSenderId: '999607488029',
    projectId: 'ai-tumor-detect',
    storageBucket: 'ai-tumor-detect.firebasestorage.app',
    iosBundleId: 'com.example.aiTumorDetect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDomf8CvWj7I1mx2FMwKpcXFytKfDsdN0Q',
    appId: '1:999607488029:web:083b75c1873baa773f00f4',
    messagingSenderId: '999607488029',
    projectId: 'ai-tumor-detect',
    authDomain: 'ai-tumor-detect.firebaseapp.com',
    storageBucket: 'ai-tumor-detect.firebasestorage.app',
    measurementId: 'G-JTBXC1LSJ5',
  );
}
